-- DROP TABLE IF EXISTS supprime une table si elle existe
-- C'est pratique si on execute ce script plusieurs fois, pour effacer et recommencer de 0

-- Attention, la syntaxe SQL est capricieuse. Pas de virugle à la fin d'une liste ce champ lors de la création d'une table
-- Attention, les valeurs rentrée lors du INSERT INTO doivent être entre simple quote 
-- A priori, REQUIRED n'existe pas, je sais pas d'où je le sortais

BEGIN;


DROP TABLE IF EXISTS "monster",
"personnages_from_user", 
"personnage_base",
"inventory",
"teams",
"users" CASCADE;

CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT NOT NULL UNIQUE, 
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "inventory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "users_id" INTEGER REFERENCES "users"("id"),
    "xp_amount" INTEGER NOT NULL,
    "powerclick_amount" INTEGER NOT NULL,
     "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "teams" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NULL UNIQUE,
    "users_id" INTEGER REFERENCES "users"("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);


CREATE TABLE IF NOT EXISTS "personnage_base" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "lvl" INTEGER NOT NULL ,
    "power_click" INTEGER NOT NULL,
    "cost" INTEGER NOT NULL ,
    "auto_click_cost" INTEGER NOT NULL,
    "growth_rate" DECIMAL(10,5) NOT NULL,
    "images" TEXT NOT NULL,
    "game_logo_img" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "personnages_from_user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "lvl" INTEGER NOT NULL ,
    "power_click" INTEGER NOT NULL,
    "cost" INTEGER NOT NULL ,
    "auto_click_cost" INTEGER NOT NULL,
    "growth_rate" DECIMAL(10,5) NOT NULL,
    "images" TEXT NOT NULL,
    "teams_id" INTEGER REFERENCES "teams"("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ

);

CREATE TABLE IF NOT EXISTS "monster" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "images" TEXT NOT NULL, 
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

INSERT INTO "users" ("username", "email", "password") VALUES 
    ('alex', 'alex@something.truc', 'testPassword');

INSERT INTO "personnage_base" ("name", "lvl", "power_click", "cost", "auto_click_cost", "growth_rate", "images", "game_logo_img" ) VALUES
    ('Cloud Strife', 0, 1, 25, 5000, 2.17, '/assets/images/cloud.jpeg', '/assets/images/ff7Logo.jpeg' ),
    (E'Y\'shtola', 0, 5, 2500, 40000, 1.97, '/assets/images/Yshtola.jpeg', '/assets/images/ff14Logo.jpeg'),
    ('Balthier', 0, 12, 9000, 100000, 2.07, '/assets/images/balthier.jpeg', '/assets/images/ff12Logo.jpeg'),
    ('Edge', 0, 24, 17800, 400500, 1.48, '/assets/images/edge.jpeg', '/assets/images/ff4Logo.jpeg'),
    ('Ramza', 0, 41, 30000, 985000, 2.55, '/assets/images/ramza.jpeg', '/assets/images/ffTacticsLogo.jpeg');

INSERT INTO "inventory" ("users_id", "xp_amount", "powerclick_amount") VALUES
    (1, 0, 1);

INSERT INTO "teams" ("name", "users_id") VALUES
    ('Hautvent', 1);

INSERT INTO "personnages_from_user" ("name", "lvl", "power_click", "cost", "auto_click_cost", "growth_rate", "images", "teams_id" ) VALUES
    ('Cloud Strife', 5, 5, 5000, 5000, 2.17, '/assets/images/cloud_strife.png',1),
    ('Yshtola', 3, 15, 12500, 40000, 1.97, '/assets/images/Yshtola.png',1),
    ('Balthier', 3, 36, 599000, 100000, 2.07, '/assets/images/balthier.jpeg',1);

INSERT INTO "monster" ("name", "images") VALUES 
    ('Shinra Soldier', '/assets/images/soldier_shinra_ff7.png');

COMMIT;

-- SELECT *  FROM users AS u INNER JOIN teams AS t ON (u.id = t.users_id) INNER JOIN personnages_from_user AS pu ON (t.id = pu.teams_id)  WHERE u.id = 1