--  Deploy ff_clicker:1.create_tables to pg



BEGIN;
CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT NOT NULL UNIQUE, 
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "tutorial_status" BOOLEAN NOT NULL DEFAULT FALSE,
    "autoclick_status" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "inventory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "users_id" INTEGER REFERENCES "users"("id"),
    "xp_amount" INTEGER NOT NULL DEFAULT 0,
    "powerclick_amount" INTEGER NOT NULL DEFAULT 1,
    "gils" INTEGER,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "personnage_base" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "lvl" INTEGER NOT NULL ,
    "power_click" INTEGER NOT NULL,
    "cost" INTEGER NOT NULL ,
    "auto_click_cost" INTEGER NOT NULL,
    "growth_rate" DECIMAL(10,5) NOT NULL,
    "images" TEXT NOT NULL,
    "game_logo_img" TEXT,
    "quotes" TEXT NOT NULL,
    "episode" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "personnages_from_user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "lvl" INTEGER NOT NULL ,
    "power_click" INTEGER NOT NULL,
    "cost" INTEGER NOT NULL ,
    "auto_click_cost" INTEGER NOT NULL,
    "growth_rate" DECIMAL(10,5) NOT NULL,
    "images" TEXT NOT NULL,
    "autoclick_statut" BOOLEAN NOT NULL,
    "users_id" INTEGER REFERENCES "users"("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "zone" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "zone_number" INTEGER NOT NULL DEFAULT 1,
    "background_img" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "stages" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "stage_number" INTEGER NOT NULL,
    "number_of_monster" INTEGER NOT NULL DEFAULT 10,
    "gold_obtainable" INTEGER NOT NULL DEFAULT 1,
    "zone_id" INTEGER REFERENCES "zone"("id")
);

CREATE TABLE IF NOT EXISTS "monster" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "image" TEXT NOT NULL,
    "pv" INTEGER NOT NULL DEFAULT 30,
    "is_boss" BOOLEAN,
    "stage_id" INTEGER REFERENCES "stages"("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

COMMIT;